// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByezoi5g3G55U3qwTqBHH4ZVm3u1Y_gLA',
    appId: '1:813595812546:web:0d28201851fde959b1d15b',
    messagingSenderId: '813595812546',
    projectId: 'facerecognition-c5376',
    authDomain: 'facerecognition-c5376.firebaseapp.com',
    storageBucket: 'facerecognition-c5376.appspot.com',
    measurementId: 'G-NYNKXXPD62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAol-LtVZH7tVA1sInv2ZZ8NCpQVeksGGA',
    appId: '1:813595812546:android:41d132ce0f868407b1d15b',
    messagingSenderId: '813595812546',
    projectId: 'facerecognition-c5376',
    storageBucket: 'facerecognition-c5376.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQwGxfrGagf_FWdp6UrICv9oqPjIa6Dwg',
    appId: '1:813595812546:ios:76f8a1ca9608f9d6b1d15b',
    messagingSenderId: '813595812546',
    projectId: 'facerecognition-c5376',
    storageBucket: 'facerecognition-c5376.appspot.com',
    iosClientId: '813595812546-cqs18p144sa8kms1f9ni51dl9fb8vkg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceRecognitionAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQwGxfrGagf_FWdp6UrICv9oqPjIa6Dwg',
    appId: '1:813595812546:ios:76f8a1ca9608f9d6b1d15b',
    messagingSenderId: '813595812546',
    projectId: 'facerecognition-c5376',
    storageBucket: 'facerecognition-c5376.appspot.com',
    iosClientId: '813595812546-cqs18p144sa8kms1f9ni51dl9fb8vkg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceRecognitionAttendanceApp',
  );
}
